language: ruby
cache: bundler
rvm:
  - 2.4.0
services:
  - postgresql
before_script:
  - bundle exec rails db:create db:migrate RAILS_ENV=test
script:
  - bundle exec rails ci:tests
deploy:
  provider: heroku
  api_key: 1cae5d22-2310-4eb7-9c98-a3b4a3d56882
  run:
    - bundle exec rails db:create db:migrate
