language: ruby
cache: bundler
rvm:
  - 2.4.0
services:
  - postgresql
before_script:
  - bundle exec rails db:create db:migrate RAILS_ENV=test
script:
  - bundle exec rails ci:tests
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: K+0SWoMqEKouyocVG44EPIYeWoFnKqsgBGLxYKG9apwD6PRva9LjG8RekAeSlR9Y+scXk8oFNvXbXxhCKnSgBNpHep/MH8ujUbOJGqPqQDSfMhFaMhXu+oHi4reROcrKhP2ZQbijwmCPLCd275KBAWBgNdVSHDGdn2NXRc9UncB2mvAIhSc3vzkwWgLkEZDElhhyXxtKlmN/MRbyuhdTZoo+WTeNpOolinHWGzO00M1UDIzVK83VNvbmTN0Xg/LkUVmkelVWN1KG7tPyFp/QRcp0/3f+cLFiBjvugwLm/xJ+nQishjIMuaQ5fM8OI6RzaccmZt8nKxocvlEHhM9gDkdsha3p13FfQARMdHdUegkaA8TY8aLolF0yuqK/6o9iaBon9k1Pg/oKODz6XH7nC65EBN+laGYDoB8cfRdnSMrrn7kEztT1SzamXyvD3D3FLlPZgpLrfPXD9XaC7zeYtXcme+xw0MTMZsnfRgfiArThTIwiWSn7aASMnMtNLgJ9pJmmRdszoYdJT9dyiMWaF3qqpAV4nrIiMvm2FmFUy5XH0j4I+RpAaZwifYDE6ulaC/ERNBPi9bGqT0RjE9zteqn2bFzbQk4zb0pERouFH+/qEXuzEfKEg2SndnugiMe6uHj+FYgAN57RumIwbc+CnMYp/FdOmbXZ3GYRCdjAqVs=
  app:
    master: rails-messaging-lions
  run:
    - bundle exec rails db:migrate
